import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowDownToLine, BookOpen, CheckCircle2, ChevronRight, ClipboardCheck, Download, FileJson, FileText, LayoutDashboard, ListChecks, RefreshCw, Save, Search, ShieldCheck, SlidersHorizontal, Upload, Users, X } from 'lucide-react';
import { criteria, modules, Profile, Criterion, basisLabel } from '@/data/criteria';
import { Answer, Answers, emptyAnswer, priority, score, statusColor, statusLabel } from '@/lib/scoring';
import { clearAudit, downloadJson, loadAudit, readJsonFile, saveAudit } from '@/lib/storage';
import './index.css';

type View = 'dashboard' | 'assessment' | 'remediation' | 'sources' | 'report';
const today = new Date().toISOString().slice(0,10);
const defaultProfile: Profile = { name:'', region:'', unitType:'企业', industry:'', multiSite:false, keyCandidate:false, secret:false, dangerous:false, crowded:false, dataStorage:false, reviewer:'', reviewDate:today };
const makeAnswers = (): Answers => Object.fromEntries(criteria.map(c => [c.id, emptyAnswer()]));

function App() {
  const [profile, setProfile] = useState<Profile>(() => loadAudit()?.profile ?? defaultProfile);
  const [answers, setAnswers] = useState<Answers>(() => loadAudit()?.answers ?? makeAnswers());
  const [view, setView] = useState<View>('dashboard');
  const [activeModule, setActiveModule] = useState('governance');
  const [query, setQuery] = useState('');
  const [showProfile, setShowProfile] = useState(!loadAudit());
  const [notice, setNotice] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const currentScore = useMemo(() => score(criteria, answers, profile, false), [answers, profile]);
  const forwardScore = useMemo(() => score(criteria, answers, profile, true), [answers, profile]);
  const applicableCount = currentScore.active.length;
  const save = () => { saveAudit({ profile, answers, savedAt:new Date().toISOString() }); setNotice('已保存到本机浏览器'); setTimeout(()=>setNotice(''),2200); };
  useEffect(() => { const t = setTimeout(save, 800); return () => clearTimeout(t); }, [profile, answers]);
  const updateAnswer = (id: string, patch: Partial<Answer>) => setAnswers(prev => ({ ...prev, [id]: { ...prev[id], ...patch } }));
  const reset = () => { if (confirm('确定清空本机审核草稿吗？此操作不可撤销。')) { clearAudit(); setProfile(defaultProfile); setAnswers(makeAnswers()); setShowProfile(true); setNotice('已清空本机草稿'); } };
  const importFile = async (file?: File) => { if (!file) return; try { const s = await readJsonFile(file); setProfile(s.profile); setAnswers(s.answers); setNotice('已导入审核档案'); } catch(e) { setNotice(e instanceof Error ? e.message : '导入失败'); } };
  const goAssessment = (m = activeModule) => { setActiveModule(m); setView('assessment'); };
  const filtered = currentScore.active.filter(c => (!query || `${c.id}${c.title}${c.prompt}${c.basis.map(b=>b.clause).join('')}`.toLowerCase().includes(query.toLowerCase())) && c.module === activeModule);
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-900">
    <header className="topbar"><div className="brand"><div className="brand-mark"><ShieldCheck size={22}/></div><div><div className="brand-title">内保合规审核台</div><div className="brand-sub">单位内部治安保卫 · 全标准版</div></div></div><div className="top-actions"><span className="status-dot"><span/>本地模式 · 不上传材料</span><button className="icon-btn" onClick={save} title="保存"><Save size={18}/></button><button className="outline-btn" onClick={()=>fileRef.current?.click()}><Upload size={16}/> 导入</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={e=>importFile(e.target.files?.[0])}/><button className="primary-btn" onClick={()=>downloadJson({profile,answers,savedAt:new Date().toISOString()})}><Download size={16}/> 导出JSON</button></div></header>
    <div className="disclaimer"><AlertTriangle size={16}/><span>内部自查辅助工具，不替代公安机关监督检查、主管部门要求或法律意见。征求意见稿内容仅作前瞻性参考。</span><button onClick={()=>setNotice('现行基线：2004版条例 + DB11/T 2552—2026；前瞻口径另行显示')}>查看口径</button></div>
    <div className="app-shell"><aside className="sidebar"><div className="profile-mini"><div className="avatar">{profile.name ? profile.name.slice(0,1) : '未'}</div><div className="profile-name">{profile.name || '未创建审核'}</div><div className="profile-meta">{profile.unitType} · {profile.industry || '待填写行业'}</div><button className="text-btn" onClick={()=>setShowProfile(true)}>编辑单位画像 <ChevronRight size={14}/></button></div><nav className="nav"><NavItem active={view==='dashboard'} icon={<LayoutDashboard size={18}/>} label="审核总览" onClick={()=>setView('dashboard')}/><NavItem active={view==='assessment'} icon={<ClipboardCheck size={18}/>} label="分模块审核" onClick={()=>goAssessment()}/><NavItem active={view==='remediation'} icon={<ListChecks size={18}/>} label="整改清单" count={currentScore.open.length} onClick={()=>setView('remediation')}/><NavItem active={view==='sources'} icon={<BookOpen size={18}/>} label="依据与差异" onClick={()=>setView('sources')}/><NavItem active={view==='report'} icon={<FileText size={18}/>} label="审核报告" onClick={()=>setView('report')}/></nav><div className="sidebar-foot"><div>审核标准库</div><strong>DB11/T 2552—2026</strong><span>第1—9章 · 附录A—H</span><span>2004版条例 · 修订征求意见稿</span><button className="danger-link" onClick={reset}>清空本机草稿</button></div></aside>
      <main className="main-content">{notice && <div className="toast"><CheckCircle2 size={16}/> {notice}</div>}{view==='dashboard' && <Dashboard profile={profile} score={currentScore} forward={forwardScore} answers={answers} onModule={goAssessment} onStart={()=>setShowProfile(true)}/>} {view==='assessment' && <Assessment activeModule={activeModule} setActiveModule={setActiveModule} modules={modules} criteria={filtered} allCriteria={currentScore.active} answers={answers} updateAnswer={updateAnswer} query={query} setQuery={setQuery} onBack={()=>setView('dashboard')}/>} {view==='remediation' && <Remediation criteria={currentScore.active} answers={answers} updateAnswer={updateAnswer} onAssess={(m)=>goAssessment(m)}/>} {view==='sources' && <Sources/>} {view==='report' && <Report profile={profile} current={currentScore} forward={forwardScore} answers={answers}/>}</main></div>
    {showProfile && <ProfileModal profile={profile} setProfile={setProfile} onClose={()=>setShowProfile(false)} onReset={()=>{setAnswers(makeAnswers());setView('dashboard');}}/>}
  </div>;
}
function NavItem({active, icon, label, count, onClick}:{active:boolean;icon:React.ReactNode;label:string;count?:number;onClick:()=>void}) { return <button className={`nav-item ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span>{count ? <b>{count}</b> : null}</button> }
function Dashboard({profile,score:sc,forward,answers,onModule,onStart}:{profile:Profile;score:ReturnType<typeof score>;forward:ReturnType<typeof score>;answers:Answers;onModule:(m:string)=>void;onStart:()=>void}) { const reviewedCount=sc.counted.filter(c=>['compliant','partial','noncompliant'].includes(answers[c.id]?.status)).length; return <div><div className="page-head"><div><div className="eyebrow">COMPLIANCE REVIEW / {profile.reviewDate || today}</div><h1>{profile.name ? `${profile.name} · 合规审核总览` : '开始一次单位合规审核'}</h1><p>基于完整 DB11/T 2552—2026、2004版条例与修订征求意见稿的双口径审核工作台。</p></div><button className="primary-btn" onClick={onStart}><SlidersHorizontal size={17}/> {profile.name?'编辑单位画像':'创建审核'}</button></div><section className="hero-grid"><div className={`score-card ${sc.level==='高风险'?'danger':''}`}><div className="score-label">现行基线完成率</div><div className="score-number">{sc.completion}<small>%</small></div><div className="score-level">{sc.level} <span>· {sc.criticalGaps.length} 个关键缺口</span></div><div className="score-track"><i style={{width:`${sc.completion}%`}}/></div><div className="score-foot">已审核 {reviewedCount} / 适用 {sc.counted.length} 项</div></div><div className="metric-card"><div className="metric-icon amber"><AlertTriangle size={20}/></div><div><span>待整改</span><strong>{sc.open.filter(c=>['partial','noncompliant'].includes(answers[c.id]?.status)).length}</strong><small>含 {sc.criticalGaps.length} 项关键项</small></div></div><div className="metric-card"><div className="metric-icon blue"><BookOpen size={20}/></div><div><span>前瞻差距</span><strong>{Math.max(0,forward.active.length-sc.active.length)}</strong><small>征求意见稿新增/强化</small></div></div></section><div className="section-head"><div><h2>模块完成情况</h2><p>点击模块进入逐项审核；重点单位、涉密涉危等项目会自动触发。</p></div><span className="muted">{sc.active.length} 个适用审核项</span></div><div className="module-grid">{modules.map(m=>{const items=sc.active.filter(c=>c.module===m.id);const reviewed=items.filter(c=>['compliant','partial','noncompliant','na'].includes(answers[c.id]?.status)).length;const pct=items.length?Math.round(reviewed/items.length*100):0;return <button className="module-card" key={m.id} onClick={()=>onModule(m.id)}><div className="module-top"><span className="module-code">{m.short}</span><ChevronRight size={16}/></div><h3>{m.label}</h3><div className="module-progress"><i style={{width:`${pct}%`}}/></div><div className="module-foot"><span>{items.length} 项</span><b>{pct}%</b></div></button>})}</div><div className="callout"><div className="callout-icon"><ShieldCheck size={22}/></div><div><strong>审核提示</strong><p>建议先完成“责任制与资源保障、机构与人员、制度与档案”三项基础模块，再进入系统技术和重点单位分级审核。</p></div><button className="text-btn" onClick={()=>onModule('governance')}>开始基础审核 <ChevronRight size={15}/></button></div></div> }
function Assessment({activeModule,setActiveModule,modules,criteria:items,allCriteria,answers,updateAnswer,query,setQuery,onBack}:{activeModule:string;setActiveModule:(s:string)=>void;modules:Array<{id:string;label:string;short:string}>;criteria:Criterion[];allCriteria:Criterion[];answers:Answers;updateAnswer:(id:string,p:Partial<Answer>)=>void;query:string;setQuery:(s:string)=>void;onBack:()=>void}) { return <div><div className="page-head compact"><div><div className="eyebrow">ASSESSMENT / FULL STANDARD</div><h1>分模块审核</h1><p>每个项目都保留来源条款、版本状态、证据提示和整改字段。</p></div><button className="outline-btn" onClick={onBack}><LayoutDashboard size={16}/> 返回总览</button></div><div className="assessment-layout"><div className="module-list">{modules.map(m=>{const count=allCriteria.filter(c=>c.module===m.id).length;return <button className={`module-nav ${activeModule===m.id?'active':''}`} onClick={()=>setActiveModule(m.id)} key={m.id}><span>{m.short}</span><div><strong>{m.label}</strong><small>{count} 项审核</small></div><ChevronRight size={15}/></button>})}</div><div className="criteria-pane"><div className="criteria-toolbar"><div><h2>{modules.find(m=>m.id===activeModule)?.label}</h2><span>{items.length} 个适用项目</span></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索条款、项目或关键词"/></div></div>{items.length===0 ? <div className="empty"><CheckCircle2 size={32}/><h3>暂无适用项目</h3><p>当前单位画像未触发该模块。</p></div> : items.map(c=><AssessmentItem key={c.id} c={c} answer={answers[c.id]} update={p=>updateAnswer(c.id,p)}/>)}</div></div></div> }
function AssessmentItem({c,answer,update}:{c:Criterion;answer:Answer;update:(p:Partial<Answer>)=>void}) { const basis=c.basis[0]; return <article className={`criterion ${answer.status==='noncompliant'?'is-danger':''}`}><div className="criterion-head"><div><div className="criterion-id">{c.id} <span className={`pill ${basis.kind==='forward'?'forward':'current'}`}>{basisLabel(basis.kind)}</span>{c.critical&&<span className="pill critical">关键项</span>}</div><h3>{c.title}</h3></div><span className="weight">权重 {c.weight}</span></div><p className="prompt">{c.prompt}</p><div className="basis-line"><BookOpen size={14}/> {basis.source} · {basis.clause}{basis.note && <em>{basis.note}</em>}</div><div className="status-row">{(['compliant','partial','noncompliant','na'] as const).map(s=><button key={s} className={`status-btn ${answer.status===s?'selected':''} ${s}`} onClick={()=>update({status:s})}>{s==='compliant'?'符合':s==='partial'?'部分符合':s==='noncompliant'?'不符合':'不适用'}</button>)}</div><div className="evidence-grid"><label>证据编号/位置<input value={answer.evidence} onChange={e=>update({evidence:e.target.value})} placeholder={c.evidence}/></label><label>整改负责人<input value={answer.owner} onChange={e=>update({owner:e.target.value})} placeholder="未整改时填写"/></label><label>整改期限<input type="date" value={answer.due} onChange={e=>update({due:e.target.value})}/></label><label>整改措施<textarea value={answer.action} onChange={e=>update({action:e.target.value})} placeholder="记录拟采取的措施"/></label></div></article> }
function Remediation({criteria:items,answers,updateAnswer,onAssess}:{criteria:Criterion[];answers:Answers;updateAnswer:(id:string,p:Partial<Answer>)=>void;onAssess:(m:string)=>void}) { const open=items.filter(c=>['partial','noncompliant'].includes(answers[c.id]?.status)); return <div><div className="page-head compact"><div><div className="eyebrow">ACTION TRACKER</div><h1>整改清单</h1><p>将部分符合和不符合项目转化为责任、期限和措施。</p></div><div className="count-badge">{open.length} 项待整改</div></div><div className="remediation-list">{open.length===0?<div className="empty"><CheckCircle2 size={34}/><h3>暂无待整改项目</h3><p>完成审核后，存在缺口的项目会自动出现在这里。</p></div>:open.map(c=><article className="remediation-item" key={c.id}><div className="remediation-main"><div className="criterion-id">{c.id} <span className={`pill ${answers[c.id].status==='noncompliant'?'critical':'forward'}`}>{priority(c,answers[c.id])}优先级</span></div><h3>{c.title}</h3><p>{c.prompt}</p><div className="basis-line"><BookOpen size={14}/> {c.basis[0].source} · {c.basis[0].clause}</div></div><div className="remediation-fields"><label>负责人<input value={answers[c.id].owner} onChange={e=>updateAnswer(c.id,{owner:e.target.value})}/></label><label>期限<input type="date" value={answers[c.id].due} onChange={e=>updateAnswer(c.id,{due:e.target.value})}/></label><label>措施<textarea value={answers[c.id].action} onChange={e=>updateAnswer(c.id,{action:e.target.value})}/></label><button className="text-btn" onClick={()=>onAssess(c.module)}>回到审核项 <ChevronRight size={14}/></button></div></article>)}</div></div> }
function Sources(){ const rows=[['现行基线','2004版条例','行政法规库正式文本','现行条例基线'],['现行/地方标准','DB11/T 2552—2026','完整第1—9章及附录A—H','2026-10-01实施'],['前瞻参考','修订征求意见稿','公开转载及新旧对照材料','非现行，不作违法结论']];return <div><div className="page-head compact"><div><div className="eyebrow">SOURCE LIBRARY</div><h1>依据与差异</h1><p>所有审核项均保留来源条款；现行基线和前瞻差距分开计算。</p></div></div><div className="source-cards">{rows.map(r=><div className="source-card" key={r[0]}><span className={`source-type ${r[0].includes('前瞻')?'amber':''}`}>{r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p><small>{r[3]}</small></div>)}</div><div className="difference"><h2>标准覆盖范围</h2><div className="coverage-grid">{['第1章 范围','第2章 规范性引用文件','第3章 术语和定义','第4章 总体要求','第5章 一般单位常态防范','第6章 重点单位常态防范','第7章 非常态防范','第8章 系统技术要求','第9章 内部检查','附录A—H'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></div></div> }
function Report({profile,current:sc,forward,answers}:{profile:Profile;current:ReturnType<typeof score>;forward:ReturnType<typeof score>;answers:Answers}) { return <div className="report-page"><div className="page-head compact no-print"><div><div className="eyebrow">REPORT / INTERNAL USE</div><h1>审核报告</h1><p>生成时间：{new Date().toLocaleString('zh-CN')}</p></div><button className="primary-btn" onClick={()=>window.print()}><FileText size={16}/> 打印报告</button></div><div className="report-sheet"><div className="report-header"><div><div className="report-kicker">单位内部治安保卫合规审核</div><h1>{profile.name || '未命名单位'}</h1><p>{profile.region || '未填写地区'} · {profile.unitType} · {profile.industry || '未填写行业'} · 审核日期 {profile.reviewDate || today}</p></div><div className={`report-score ${sc.level==='高风险'?'danger':''}`}><strong>{sc.completion}%</strong><span>{sc.level}</span></div></div><div className="report-warning"><AlertTriangle size={16}/> 本报告为内部自查辅助，不等同于公安机关、主管部门或其他监管机构的法定合格证明。征求意见稿项目仅作前瞻性参考。</div><div className="report-stats"><div><span>适用项目</span><strong>{sc.counted.length}</strong></div><div><span>关键缺口</span><strong>{sc.criticalGaps.length}</strong></div><div><span>待整改</span><strong>{sc.open.length}</strong></div><div><span>前瞻差距项目</span><strong>{Math.max(0,forward.active.length-sc.active.length)}</strong></div></div><h2>重点缺口与整改建议</h2><div className="report-table">{sc.open.slice(0,20).map(c=><div className="report-row" key={c.id}><b>{c.id}</b><span>{c.title}</span><span>{statusLabel[answers[c.id].status]}</span><span>{answers[c.id].owner || '待指定'}</span><span>{answers[c.id].due || '待定'}</span></div>)}{sc.open.length===0&&<div className="empty">暂无缺口</div>}</div><div className="report-foot">依据：DB11/T 2552—2026（第1—9章及附录A—H）、2004版《企业事业单位内部治安保卫条例》；征求意见稿为前瞻参考。审核人：{profile.reviewer || '未填写'}</div></div></div> }
function ProfileModal({profile,setProfile,onClose,onReset}:{profile:Profile;setProfile:(p:Profile)=>void;onClose:()=>void;onReset:()=>void}){const [draft,setDraft]=useState(profile);const set=(key:keyof Profile,val:unknown)=>setDraft({...draft,[key]:val});return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><div className="eyebrow">UNIT PROFILE</div><h2>创建 / 编辑单位画像</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><p className="modal-note">画像只用于决定审核项适用范围，不上传至服务器。</p><div className="form-grid"><label className="wide">单位名称<input value={draft.name} onChange={e=>set('name',e.target.value)} placeholder="例如：某科技有限公司"/></label><label>所属地区<input value={draft.region} onChange={e=>set('region',e.target.value)} placeholder="省/市/区"/></label><label>单位类型<select value={draft.unitType} onChange={e=>set('unitType',e.target.value)}><option>企业</option><option>事业单位</option><option>机关</option><option>团体</option><option>民办非企业</option></select></label><label>所属行业<input value={draft.industry} onChange={e=>set('industry',e.target.value)} placeholder="例如：互联网、医疗、教育"/></label><label>审核人<input value={draft.reviewer} onChange={e=>set('reviewer',e.target.value)} placeholder="姓名/部门"/></label></div><div className="trigger-title">适用性触发条件</div><div className="check-grid">{([['multiSite','多地机构/设施/场站'],['keyCandidate','可能属于治安保卫重点单位'],['secret','涉及国家秘密/涉密载体'],['dangerous','涉及危险物品/菌种/武器弹药'],['crowded','人员密集/大型活动场所'],['dataStorage','重要数据存储/重要高科技或互联网企业']] as [keyof Profile,string][]).map(([k,l])=><label className="check-item" key={k}><input type="checkbox" checked={Boolean(draft[k])} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div><div className="modal-actions"><button className="outline-btn" onClick={()=>{onReset();onClose()}}>重置审核答案</button><div><button className="outline-btn" onClick={onClose}>取消</button><button className="primary-btn" onClick={()=>{setProfile({...draft,keyCandidate:draft.keyCandidate||draft.secret||draft.dangerous||draft.crowded||draft.dataStorage});onClose()}}>保存画像</button></div></div></div></div> }
export default App;
